In [ ]:
pip install -U fortran-magic

Requirement already up-to-date: fortran-magic in /usr/local/lib/python3.6/dist-packages (0.7)


In [ ]:

%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

/usr/local/lib/python3.6/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
assert ran_the_first_cell, "Oh noes!"

In [ ]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [ ]:
#mycode
l2=[5.6,'five',100,"seven"]
l2


[5.6, 'five', 100, 'seven']

In [ ]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [ ]:
#mycode
first2 = l2[0]
second2 = l2[1]
print("primero:", first)
print("segundo:", second)

primero: 1
segundo: two


In [ ]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [ ]:
#mycode
last2 = l2[-1]
penultimate2 = l2[-2]
print("ultimo:", last2)
print("penultimo:", penultimate2)

ultimo: seven
penultimo: 100


In [ ]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [16]:
#mycode
sublist2 = l2[0:2]
sublist2

[5.6, 'five']

In [17]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [18]:
#mycode
first_three2 = l2[:4]
first_three2

[5.6, 'five', 100, 'seven']

In [19]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [20]:
#mycode
after_three = l2[1:]
after_three

['five', 100, 'seven']

In [21]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [23]:
l2= ['i', 'j', 'k', 'h', 'l', 'm', 'n']
l2[1:7:3]

['j', 'l']

In [24]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [25]:
#mycode
l2[::-1]

['n', 'm', 'l', 'h', 'k', 'j', 'i']

In [26]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [27]:
#mycode
l2 = [6, 7, 8, 9, 10, 11, 12]
print("antes:", l2)
l2.append('eleven')
print("despues:", l2)

antes: [6, 7, 8, 9, 10, 11, 12]
despues: [6, 7, 8, 9, 10, 11, 12, 'eleven']


In [28]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [29]:
#mycode
l2 = [1, 2, 3, 4, 5]
[y ** 2 for y in l2]

[1, 4, 9, 16, 25]


# Review: Python Lists

## Dictionaries

In [30]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [37]:
#mycode
names_ages = {'David': 23, 'Alejandra': 19, 'Adrian': 9}
names_ages

{'Adrian': 9, 'Alejandra': 19, 'David': 23}

In [38]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [39]:
#mycode
names_ages['Adrian']=8
names_ages

{'Adrian': 8, 'Alejandra': 19, 'David': 23}

In [40]:
del philosophers['David']
philosophers

KeyError: ignored

In [42]:

#mycode
del names_ages['Adrian']
names_ages

KeyError: ignored

In [36]:
# No slicing.
#philosophers['Bertrand':'Immanuel']

# Review: Python Dictionaries

In [49]:

# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]
b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [44]:
#mycode
a2 = [[11, 12, 13],
     [21, 22, 23],
     [31, 32, 33],
     [41, 42, 43]]
b2 = [[10, 20, 30, 40],
     [20, 30, 40, 50]]

In [45]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [46]:
#mycode
def matmul2(A, B):
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [50]:
%%time
matmul(a, b)

CPU times: user 28 µs, sys: 5 µs, total: 33 µs
Wall time: 36.7 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [48]:
#mycode
%%time
matmul2(a2, b2)

CPU times: user 25 µs, sys: 0 ns, total: 25 µs
Wall time: 28.1 µs


[[350, 580, 810, 1040],
 [650, 1080, 1510, 1940],
 [950, 1580, 2210, 2840],
 [1250, 2080, 2910, 3740]]

In [51]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.8355686394144609, 0.9966194459408912, 0.8606428049291813],
 [0.9666305492155056, 0.03873107029041445, 0.07059393248869539]]

In [53]:
#mycode
import random
def random_matrix2(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out
randm2 = random_matrix2(5, 4)
randm2

[[0.7891428871249786,
  0.8161650308858187,
  0.273663240077333,
  0.4029842997604558],
 [0.18500396003279052,
  0.23007624139031468,
  0.8439939155896681,
  0.3330464256035949],
 [0.9837100845501954,
  0.2110563513263639,
  0.7981136530220118,
  0.5501378615631763],
 [0.04811922027571425,
  0.08677919149840885,
  0.21014323557505865,
  0.7958870628152666],
 [0.03729071365798575,
  0.6397419609745949,
  0.9957498688289754,
  0.8346815193552537]]

In [54]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 6.87 s, sys: 8.47 ms, total: 6.88 s
Wall time: 6.89 s


In [55]:
#mycode
%%time
randa2 = random_matrix(1400, 1200)
randb2 = random_matrix(20, 100)
x2 = matmul(randa2, randb2)

CPU times: user 709 ms, sys: 49.1 ms, total: 758 ms
Wall time: 763 ms


In [56]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [57]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [58]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [59]:
#mycode
list_data2 = [float(i) for i in range(1000000)]
array_data2 = np.array(list_data2)

In [60]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 8.09 ms, sys: 0 ns, total: 8.09 ms
Wall time: 8.11 ms


333328333350000.0

In [61]:
#mycode
%%time
python_dot_product(list_data2, list_data2)

CPU times: user 78.3 ms, sys: 0 ns, total: 78.3 ms
Wall time: 79.6 ms


3.3333283333312755e+17

In [62]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 216 µs, sys: 0 ns, total: 216 µs
Wall time: 223 µs


333328333350000.0

In [63]:
#mycode
%%time
fortran_dot_product(array_data2, array_data2)

CPU times: user 2.04 ms, sys: 0 ns, total: 2.04 ms
Wall time: 2.11 ms


3.3333283333312755e+17

# Why is the Python Version so Much Slower?

In [64]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [66]:
#mycode.
def mul_elemwise2(xs, ys):
    return [x * y for x, y in zip(xs, ys)]
mul_elemwise2([2,4,6,8], [4,5+ 2j, 7.8, 'five'])

[8, (20+8j), 46.8, 'fivefivefivefivefivefivefivefive']

In [67]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


In [68]:
#mycode
source_code2 = 'a * b * c'
bytecode2 = compile(source_code2, '', 'eval')
import dis; dis.dis(bytecode2)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 BINARY_MULTIPLY
              6 LOAD_NAME                2 (c)
              8 BINARY_MULTIPLY
             10 RETURN_VALUE


# Why is the Python Version so Slow?

In [69]:
import numpy as np
data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [72]:
#mycode
data2 = np.array([1,2,3,5])
data2

array([1, 2, 3, 5])

In [73]:
data2 * data2

array([ 1,  4,  9, 25])

In [74]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 2.44 ms, sys: 29 µs, total: 2.47 ms
Wall time: 1.37 ms


333328333350000.0

In [75]:
#mycode
%%time
(array_data2 * array_data2).sum()

CPU times: user 3.11 ms, sys: 4.12 ms, total: 7.24 ms
Wall time: 9.7 ms


3.333328333335e+17

In [76]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 2.06 ms, sys: 3.01 ms, total: 5.06 ms
Wall time: 4.34 ms


333328333350000.0

In [77]:
#mycode
%%time
array_data.dot(array_data)

CPU times: user 496 µs, sys: 0 ns, total: 496 µs
Wall time: 275 µs


333328333350000.0

In [78]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 229 µs, sys: 20 µs, total: 249 µs
Wall time: 256 µs


333328333350000.0

In [79]:
#mycode
%%time
fortran_dot_product(array_data2, array_data2)

CPU times: user 1.67 ms, sys: 53 µs, total: 1.72 ms
Wall time: 1.73 ms


3.3333283333312755e+17

In [80]:
# Numpy won't allow us to write a string into an int array.
#data[0] = "foo"

In [81]:
# We also can't grow an array once it's created.
#data.append(3)

In [82]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

In [84]:
#mycode
four_by_four = data2.reshape(2,2)
four_by_four

array([[1, 2],
       [3, 5]])

# What's in an Array?

In [85]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [87]:
#mycode
arr2 = np.array([1,2,3,5,7,11], dtype='int16').reshape(2, 3)
print("Array:\n", arr2, sep='')
print("===========")
print("DType:", arr2.dtype)
print("Shape:", arr2.shape)
print("Strides:", arr2.strides)
print("Data:", arr2.data.tobytes())

Array:
[[ 1  2  3]
 [ 5  7 11]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x05\x00\x07\x00\x0b\x00'



# Core Operations

# UFuncs

In [88]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
#mycode
data2 =np.arange(12).reshape(4, 3)
data2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [91]:
#mycode
data2*data2

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [92]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [93]:
#mycode
np.sqrt(data2)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [94]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [95]:
#mycode 
(data2%5)==0

array([[ True, False, False],
       [False, False,  True],
       [False, False, False],
       [False,  True, False]])

In [96]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [97]:
#mycode
((data2 % 2) == 0) | ((data2 % 3) == 0)

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True, False]])

In [98]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [99]:
data2 @ data2.T

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

# UFuncs Review

In [100]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [102]:
#mycode
tangs = np.tan(np.linspace(4, 34.1, 100))
tanhs = np.tanh(np.linspace(4, 34.1, 100))
tangs

array([ 1.15782128e+00,  2.31123440e+00,  9.55218190e+00, -4.93994803e+00,
       -1.81418666e+00, -9.56145887e-01, -4.94132851e-01, -1.56153437e-01,
        1.50253566e-01,  4.86981074e-01,  9.45171658e-01,  1.78970515e+00,
        4.79756362e+00, -1.01149214e+01, -2.34828613e+00, -1.17140432e+00,
       -6.27132733e-01, -2.61840337e-01,  4.79860931e-02,  3.67284974e-01,
        7.69763325e-01,  1.42857192e+00,  3.15779512e+00,  3.78071719e+02,
       -3.21682171e+00, -1.44478045e+00, -7.78222346e-01, -3.73300317e-01,
       -5.32896592e-02,  2.56195430e-01,  6.19786518e-01,  1.15893264e+00,
        2.31424730e+00,  9.59615705e+00, -4.92792082e+00, -1.81215193e+00,
       -9.55237880e-01, -4.93542552e-01, -1.55667337e-01,  1.50738879e-01,
        4.87568317e-01,  9.46070577e-01,  1.79170146e+00,  4.80898706e+00,
       -1.00661276e+01, -2.34519805e+00, -1.17027919e+00, -6.26471721e-01,
       -2.61333299e-01,  4.84617612e-02,  3.67823650e-01,  7.70519362e-01,
        1.43001596e+00,  

In [103]:
#mycode
tangs[0]

1.1578212823495775

In [104]:
sines[:3]  # First three elements

array([0.        , 0.34185385, 0.64251645])

In [105]:
#mycode
tangs[:4]

array([ 1.15782128,  2.3112344 ,  9.5521819 , -4.93994803])

In [106]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [109]:
#mycode
tangs[50:]

array([ 3.67823650e-01,  7.70519362e-01,  1.43001596e+00,  3.16300970e+00,
        4.60737439e+02, -3.21144459e+00, -1.44331629e+00, -7.77460652e-01,
       -3.72759716e-01, -5.28137591e-02,  2.56701205e-01,  6.20443572e-01,
        1.16004521e+00,  2.31726683e+00,  9.64053457e+00, -4.91594974e+00,
       -1.81012069e+00, -9.54330697e-01, -4.92952529e-01, -1.55181308e-01,
        1.51224262e-01,  4.88155833e-01,  9.46970305e-01,  1.79370117e+00,
        4.82046276e+00, -1.00177977e+01, -2.34211683e+00, -1.16915530e+00,
       -6.25811102e-01, -2.60826387e-01,  4.89374512e-02,  3.68362515e-01,
        7.71275953e-01,  1.43146197e+00,  3.16823996e+00,  5.89668781e+02,
       -3.20608383e+00, -1.44185413e+00, -7.76699520e-01, -3.72219307e-01,
       -5.23378828e-02,  2.57207103e-01,  6.21101014e-01,  1.16115901e+00,
        2.32029300e+00,  9.68532001e+00, -4.90403438e+00, -1.80809294e+00,
       -9.53424335e-01, -4.92362782e-01])

In [110]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [111]:
tangs[::50]

array([1.15782128, 0.36782365])

In [112]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [113]:
#mycode
print("tan:\n", tangs)
print("tan > 0.25:\n", tangs > 0.25)
print("tan[tan > 0.25]:\n", tangs[tangs > 0.25])

tan:
 [ 1.15782128e+00  2.31123440e+00  9.55218190e+00 -4.93994803e+00
 -1.81418666e+00 -9.56145887e-01 -4.94132851e-01 -1.56153437e-01
  1.50253566e-01  4.86981074e-01  9.45171658e-01  1.78970515e+00
  4.79756362e+00 -1.01149214e+01 -2.34828613e+00 -1.17140432e+00
 -6.27132733e-01 -2.61840337e-01  4.79860931e-02  3.67284974e-01
  7.69763325e-01  1.42857192e+00  3.15779512e+00  3.78071719e+02
 -3.21682171e+00 -1.44478045e+00 -7.78222346e-01 -3.73300317e-01
 -5.32896592e-02  2.56195430e-01  6.19786518e-01  1.15893264e+00
  2.31424730e+00  9.59615705e+00 -4.92792082e+00 -1.81215193e+00
 -9.55237880e-01 -4.93542552e-01 -1.55667337e-01  1.50738879e-01
  4.87568317e-01  9.46070577e-01  1.79170146e+00  4.80898706e+00
 -1.00661276e+01 -2.34519805e+00 -1.17027919e+00 -6.26471721e-01
 -2.61333299e-01  4.84617612e-02  3.67823650e-01  7.70519362e-01
  1.43001596e+00  3.16300970e+00  4.60737439e+02 -3.21144459e+00
 -1.44331629e+00 -7.77460652e-01 -3.72759716e-01 -5.28137591e-02
  2.56701205e-01  6

In [114]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [115]:
#mycode
print(tangs)
tangs[[1, 3, 6]]

[ 1.15782128e+00  2.31123440e+00  9.55218190e+00 -4.93994803e+00
 -1.81418666e+00 -9.56145887e-01 -4.94132851e-01 -1.56153437e-01
  1.50253566e-01  4.86981074e-01  9.45171658e-01  1.78970515e+00
  4.79756362e+00 -1.01149214e+01 -2.34828613e+00 -1.17140432e+00
 -6.27132733e-01 -2.61840337e-01  4.79860931e-02  3.67284974e-01
  7.69763325e-01  1.42857192e+00  3.15779512e+00  3.78071719e+02
 -3.21682171e+00 -1.44478045e+00 -7.78222346e-01 -3.73300317e-01
 -5.32896592e-02  2.56195430e-01  6.19786518e-01  1.15893264e+00
  2.31424730e+00  9.59615705e+00 -4.92792082e+00 -1.81215193e+00
 -9.55237880e-01 -4.93542552e-01 -1.55667337e-01  1.50738879e-01
  4.87568317e-01  9.46070577e-01  1.79170146e+00  4.80898706e+00
 -1.00661276e+01 -2.34519805e+00 -1.17027919e+00 -6.26471721e-01
 -2.61333299e-01  4.84617612e-02  3.67823650e-01  7.70519362e-01
  1.43001596e+00  3.16300970e+00  4.60737439e+02 -3.21144459e+00
 -1.44331629e+00 -7.77460652e-01 -3.72759716e-01 -5.28137591e-02
  2.56701205e-01  6.20443

array([ 2.3112344 , -4.93994803, -0.49413285])

In [116]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [117]:
#mycode
unsorted_data2 = np.array([5,7,4,-3,12,6])

In [118]:

sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [119]:
#mycode
sort_indices2 = np.argsort(unsorted_data2)
sort_indices2

array([3, 2, 0, 5, 1, 4])

In [120]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [121]:
#mycode
unsorted_data2[sort_indices2]

array([-3,  4,  5,  6,  7, 12])

In [122]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [123]:
#mycode
market_caps2 = np.array([1,2,3,1,5]) 
assets2 = np.array(['E', 'F', 'G', 'H', 'I'])

In [124]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [125]:
#MYCODE
sort_by_mcap2 = np.argsort(market_caps2)
assets2[sort_by_mcap2]

array(['E', 'H', 'F', 'G', 'I'], dtype='<U1')

In [126]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))


Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [127]:
#MYCODE
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [128]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


In [129]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [130]:
#mycode
data2 = np.arange(36).reshape(6, 6)
data2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [131]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [132]:
#mycode
data2[:3,:3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [133]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [137]:
#mycode
data2[:3,[1,-1]]

array([[ 1,  5],
       [ 7, 11],
       [13, 17]])

In [138]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [139]:
#mycode
data2[(data2[:, 0] % 2) == 0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# Selections Review

In [140]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [141]:
variance(np.random.standard_normal(1000))


1.0313627371267216

In [142]:
#mycode
variance(np.random.standard_normal(2000))

0.9521636431599496

In [143]:
data = np.arange(30)
data.mean()

14.5

In [144]:
#mycode
data2 = np.arange(60)
data2.mean()

29.5

In [145]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [148]:
#mycode
data2 = np.arange(50).reshape(5, 10)
data2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [149]:
data.mean()

14.5

In [150]:
#mycode
data2.mean()

24.5

In [151]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [152]:
#mycode
data2.mean(axis=0)

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29.])

In [153]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [154]:
#mycode
data2.mean(axis=1)

array([ 4.5, 14.5, 24.5, 34.5, 44.5])

# Broadcasting

In [155]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [156]:
#mycode
row2 = np.array([1,2,3,5])
column2 = np.array([[2], [6], [7]])
print("Row:\n", row2, sep='')
print("Column:\n", column2, sep='')

Row:
[1 2 3 5]
Column:
[[2]
 [6]
 [7]]


In [157]:
row + column


array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [158]:
#mycode
row2*column2

array([[ 2,  4,  6, 10],
       [ 6, 12, 18, 30],
       [ 7, 14, 21, 35]])

In [159]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [160]:
#mycode
print("Data:\n", data2, sep='')
print("Mean:\n", data2.mean(axis=0), sep='')
print("Data - Mean:\n", data2 - data2.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Mean:
[20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
Data - Mean:
[[-20. -20. -20. -20. -20. -20. -20. -20. -20. -20.]
 [-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]
 [ 20.  20.  20.  20.  20.  20.  20.  20.  20.  20.]]


# Broadcasting Review

# Selection in Pandas

In [161]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [162]:

#mycode
s2 = pd.Series(index=['onu', 'sod', 'sert', 'ortauc', 'ocnic'],data=[11,21,31,41,51])
s2

onu       11
sod       21
sert      31
ortauc    41
ocnic     51
dtype: int64

# There are two pieces to a Series: the index and the values

In [163]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [164]:
#mycod
s2.iloc[0]

11

In [165]:
# ... or by label.
s.loc['a']

1

In [166]:
#mycod
s2.loc['onu']

11

In [167]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [168]:
#mycod
s2.iloc[:2]

onu    11
sod    21
dtype: int64

In [169]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [171]:
#mycod
s2.loc[:'sod ']

onu    11
sod    21
dtype: int64

In [173]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -2]]

a    1
d    4
dtype: int64

In [174]:
#mycod
s2.iloc[[1,-1]]

sod      21
ocnic    51
dtype: int64

In [175]:
# As does boolean masking.
s.loc[s > 3]

d    4
e    5
dtype: int64

In [176]:
#mycod
s2.loc[s2>2]

onu       11
sod       21
sert      31
ortauc    41
ocnic     51
dtype: int64

In [177]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [178]:
#mycode
other_s2=pd.Series({'uno': 11.0, 'dos': 22.0, 'tres': 33.0, 'cuatro': 44.0})
other_s2

uno       11.0
dos       22.0
tres      33.0
cuatro    44.0
dtype: float64

In [179]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [180]:
#mycode
s2+other_s2

cuatro   NaN
dos      NaN
ocnic    NaN
onu      NaN
ortauc   NaN
sert     NaN
sod      NaN
tres     NaN
uno      NaN
dtype: float64

In [181]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [182]:

#mycode
(s2 + other_s2).fillna(0.0)

cuatro    0.0
dos       0.0
ocnic     0.0
onu       0.0
ortauc    0.0
sert      0.0
sod       0.0
tres      0.0
uno       0.0
dtype: float64

In [ ]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

In [184]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [185]:
#mycode
aapl.iloc[:3,:3]

NameError: ignored

In [186]:
#mycode
aapl.iloc[:3,:3]

NameError: ignored

In [187]:
#mycode
aapl.loc[pd.Timestamp('2010-02-08'):pd.Timestamp('2010-02-12'), ['Low', 'Open']]

NameError: ignored

# Rolling Operations

In [188]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

In [189]:
#mycode
aapl.rolling(10)[['Low', 'Open']].mean().plot();

NameError: ignored

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
#mycode
aapl.drop('High', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

In [ ]:

#mycode
aapl['Adj Close'].pct_change().ewm(span=30).std().plot();

In [ ]:
from avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
#mycode
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Number of Stores'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
#mycode
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread2");
plt.legend(bbox_to_anchor=(2, 2));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);